spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oadb
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    root: info
    web: trace
    org.xdq.demo: debug

pagehelper:
  reasonable: true
  helper-dialect: mysql
server:
  port: 9999

# 自定义配置
oa:
  token:
    expire-time: 999999999 #令牌的过期时间，单位：秒
  anonurls: #无需登录直接可以访问的资源路径，可以使用ant格式
    - /security/login # 表示放行登录接口地址
    - /t
    - /res/** # ant地址样式
    - /info/**
  user-avatar-dir: D:/avatars #指定用户头像存放目录

